### ISSUE TITLE
"/usr/bin/fluid" does not exist

### ISSUE THREAD

**Issue by mxmlnkn** [LeMonADE-project/LeMonADE-Viewer#11]
I get this error when trying to compile LeMonADE-Viewer with CMake. I think fluid is not even needed for the viewer, so I added `set(FLTK_SKIP_FLUID TRUE)` before `find_package(FLTK REQUIRED)` which makes it compile without problems. Maybe this line should be added upstream.

**Comment by Bondoki** [comment]
closed by #16
