### ISSUE TITLE
Viewer option '--script' need revision

### ISSUE THREAD

**Issue by tonimueller** [LeMonADE-project/LeMonADE-Viewer#18]
At the moment the options works as follows: 
```shell
--script '!setColor:0-0=(1,1,0);!setRadius:0-127=0.6\n;!setColorLinks:2=(0.5,0.5,0.5);'
```
with the correct output in the viewer, put the command line shows 
```shell
command: !setColor
line   : !setColor:0-0=(1,1,0
command: !setRadius
line   : !setRadius:0-127=0.6\
!SetRadius in CommandSetRadius 
command: !setColorLinks
line   : !setColorLinks:2=(0.5,0.5,0.5
```
Thus, there are some parsing Problems...

Suggestion: 
- keep a string option and fix the parsing problems
- add the possibility to use a script-file where all commands are written in

**Comment by MartinWenge** [comment]
closed by #19
